import Image from './images/mirror.jpg';
import DiagnosticIcon from './images/DiagnosticIcon.png';
import SurgeryIcon from './images/SurgeryIcon.png';
import OrthodonticIcon from './images/OrthodonticIcon.png';
import PeriodonticIcon from './images/PeriodonticIcon.png';
import ImplantologyIcon from './images/ImplantologyIcon.png';
import PreservationIcon from './images/PreservationIcon.png';
import Philosophy from './images/Philosophy.png';
import Production from './images/Production.png';
import Quality from './images/Quality.png';

const products = [
	{
		id: 1,
		mainCategory: 'Diagnostics',
		subCategory: 'Dental Mirrors',
		productName: 'Mouth Mirror',
		article: 'SG-01',
		icon: `${DiagnosticIcon}`,
		subCategoryImg: `${Image}`,
		productImg: `${Image}`,
	},
	{
		id: 2,
		mainCategory: 'Diagnostics',
		subCategory: 'Dental Mirrors',
		productName: 'Mouth Mirror',
		article: 'SG-02',
		subCategoryImg: `${Image}`,
		productImg: `${Image}`,
		icon: `${DiagnosticIcon}`,
	},
	{
		id: 3,
		mainCategory: 'Diagnostics',
		subCategory: 'Dressing Forceps',
		productName: 'Pliers Slender Beak 160MM',
		article: 'SG-03',
		subCategoryImg: `${Image}`,
		productImg: `${Image}`,
		icon: `${DiagnosticIcon}`,
	},
	{
		id: 4,
		mainCategory: 'Diagnostics',
		subCategory: 'Dressing Forceps',
		productName: 'Dressing Pliers 130MM',
		article: 'SG-04',
		subCategoryImg: `${Image}`,
		productImg: `${Image}`,
		icon: `${DiagnosticIcon}`,
	},
	{
		id: 5,
		mainCategory: 'Dental Surgery',
		subCategory: 'Scalpel handles',
		productName: 'Scalpel Handle',
		article: 'SG-05',
		subCategoryImg: `${Image}`,
		productImg: `${Image}`,
		icon: `${SurgeryIcon}`,
	},
	{
		id: 6,
		mainCategory: 'Dental Surgery',
		subCategory: 'Extraction Foreceps',
		productName: 'Forcep',
		article: 'SG-06',
		subCategoryImg: `${Image}`,
		productImg: `${Image}`,
		icon: `${SurgeryIcon}`,
	},
	{
		id: 7,
		mainCategory: 'Orthodontic',
		subCategory: 'Orthodontic Pliers',
		productName: 'Plier',
		article: 'SG-07',
		subCategoryImg: `${Image}`,
		productImg: `${Image}`,
		icon: `${OrthodonticIcon}`,
	},
	{
		id: 8,
		mainCategory: 'Orthodontic',
		subCategory: 'Bracket Holders',
		productName: 'Holder',
		article: 'SG-08',
		subCategoryImg: `${Image}`,
		productImg: `${Image}`,
		icon: `${OrthodonticIcon}`,
	},
	{
		id: 9,
		mainCategory: 'Periodontic',
		subCategory: 'Knives Hollow Handle',
		productName: 'Knives',
		article: 'SG-09',
		subCategoryImg: `${Image}`,
		productImg: `${Image}`,
		icon: `${PeriodonticIcon}`,
	},
	{
		id: 10,
		mainCategory: 'Periodontic',
		subCategory: 'Scalar Solid Handle',
		productName: 'Solid Handle Scalar',
		article: 'SG-10',
		subCategoryImg: `${Image}`,
		productImg: `${Image}`,
		icon: `${PeriodonticIcon}`,
	},
	{
		id: 11,
		mainCategory: 'Implantology',
		subCategory: 'Sinus Lift Instruments',
		productName: 'Lift Instrument',
		article: 'SG-11',
		subCategoryImg: `${Image}`,
		productImg: `${Image}`,
		icon: `${ImplantologyIcon}`,
	},
	{
		id: 12,
		mainCategory: 'Implantology',
		subCategory: 'Bone Calipers',
		productName: 'Caliper',
		article: 'SG-12',
		subCategoryImg: `${Image}`,
		productImg: `${Image}`,
		icon: `${ImplantologyIcon}`,
	},
	{
		id: 13,
		mainCategory: 'Preservation',
		subCategory: 'Excavators',
		productName: 'Excavator',
		article: 'SG-13',
		subCategoryImg: `${Image}`,
		productImg: `${Image}`,
		icon: `${PreservationIcon}`,
	},
	{
		id: 14,
		mainCategory: 'Preservation',
		subCategory: 'Amalgam Carrier & Well',
		productName: 'Carrier',
		article: 'SG-14',
		subCategoryImg: `${Image}`,
		productImg: `${Image}`,
		icon: `${PreservationIcon}`,
	},
	{
		id: 15,
		mainCategory: 'Preservation',
		subCategory: 'Amalgam Carrier & Well',
		productName: 'Carrier',
		article: 'SG-15',
		subCategoryImg: `${Image}`,
		productImg: `${Image}`,
		icon: `${PreservationIcon}`,
	},
	{
		id: 16,
		mainCategory: 'Preservation',
		subCategory: 'Amalgam Carrier & Well',
		productName: 'Carrier',
		article: 'SG-16',
		subCategoryImg: `${Image}`,
		productImg: `${Image}`,
		icon: `${PreservationIcon}`,
	},
	{
		id: 17,
		mainCategory: 'Preservation',
		subCategory: 'Amalgam Carrier & Well',
		productName: 'Carrier',
		article: 'SG-17',
		subCategoryImg: `${Image}`,
		productImg: `${Image}`,
		icon: `${PreservationIcon}`,
	},
	{
		id: 18,
		mainCategory: 'Preservation',
		subCategory: 'Amalgam Carrier & Well',
		productName: 'Carrier',
		article: 'SG-18',
		subCategoryImg: `${Image}`,
		productImg: `${Image}`,
		icon: `${PreservationIcon}`,
	},
	{
		id: 19,
		mainCategory: 'Preservation',
		subCategory: 'Amalgam Carrier & Well',
		productName: 'Carrier',
		article: 'SG-19',
		subCategoryImg: `${Image}`,
		productImg: `${Image}`,
		icon: `${PreservationIcon}`,
	},
	{
		id: 20,
		mainCategory: 'Preservation',
		subCategory: 'Amalgam Carrier & Well',
		productName: 'Carrier',
		article: 'SG-20',
		subCategoryImg: `${Image}`,
		productImg: `${Image}`,
		icon: `${PreservationIcon}`,
	},
];

const about = [
	{
		icon: `${Philosophy}`,
		title: 'Philosophy',
		statement: 'To offer the highest quality with innovation and continuously improving the design and function of the instruments. ',
	},
	{
		icon: `${Production}`,
		title: 'Production',
		statement: 'All instruments are made in Pakistan. Our workforce is experienced to handle bulk orders.',
	},
	{
		icon: `${Quality}`,
		title: 'Quality',
		statement: 'Achieving and maintaining the highest quality requires a good blend of tradition and innovation.',
	},
];

const navigation = [
	{
		id: 1,
		title: 'Home',
		path: '/',
	},
	{
		id: 2,
		title: 'About SurgiGlass',
		path: '/about',
	},
	{
		id: 3,
		title: 'Our Products',
		path: '/products',
	},
	{
		id: 4,
		title: 'Get Quotation',
		path: '/quotation',
	},
	{
		id: 5,
		title: 'Contact Us',
		path: '/contact',
	},
];

export default products;
export { about, navigation };
